# icons.py

from PyQt6.QtGui import QIcon
import resources

ICON_MAP = {
    "0":":/icons/Icojam-Blue-Bits-Thumbs-up.256.png",
    "1":":/icons/Icojam-Blue-Bits-Folder-settings.256.png",
    "2":":/icons/download_selected_icon.png",
    "3":":/icons/icons8-data-encryption-80.png",
    "4":":/icons/icons8-view-94.png",
    "5":":/icons/icons8-trash-can-96.png",
    "6":":/icons/Icojam-Blue-Bits-Document-check.256.png",
    "7":":/icons/button_pause_icon.png",
    "8":":/icons/Icojam-Blue-Bits-Folder-images.256.png",
    "9":":/icons/Icojam-Blue-Bits-Star-rating.256.png",
    "10":":/icons/clear_icon.png",
    "11":":/icons/download_folder_icon.png",
    "12":":/icons/info_icon.png",
    "13":":/icons/Icojam-Blue-Bits-Pen-write.256.png",
    "14":":/icons/icons8-add-file-94.png",
    "15":":/icons/icons8-symlink-file-96.png",
    "16":":/icons/plus_icon.png",
    "17":":/icons/main_icon.png",
    "18":":/icons/Icojam-Blue-Bits-Document-empty.256.png",
    "19":":/icons/yes_icon.png",
    "20":":/icons/Icojam-Blue-Bits-Document-delete.256.png",
    "21":":/icons/Icojam-Blue-Bits-Document-arrow-left.256.png",
    "22":":/icons/open_file_icon.png",
    "23":":/icons/Icojam-Blue-Bits-Database-remove.256.png",
    "24":":/icons/Icojam-Blue-Bits-Database-arrow-down.256.png",
    "25":":/icons/icons8-database-administrator-94.png",
    "26":":/icons/Icojam-Blue-Bits-Warning.256.png",
    "27":":/icons/Icojam-Blue-Bits-Database-arrow-left.256.png",
    "28":":/icons/Icojam-Blue-Bits-Folder-arrow-left.256.png",
    "29":":/icons/Icojam-Blue-Bits-Arrow-up.256.png",
    "30":":/icons/Icojam-Blue-Bits-Document-settings.256.png",
    "31":":/icons/minus_icon.png",
    "32":":/icons/Icojam-Blue-Bits-Symbol-delete.256.png",
    "33":":/icons/Icojam-Blue-Bits-Folder-arrow-down.256.png",
    "34":":/icons/icons8-add-subnode-96.png",
    "35":":/icons/Icojam-Blue-Bits-Document-checkbox.256.png",
    "36":":/icons/Icojam-Blue-Bits-Symbol-check.256.png",
    "37":":/icons/Icojam-Blue-Bits-Question-faq.256.png",
    "38":":/icons/toggle_icon.png",
    "39":":/icons/Icojam-Blue-Bits-Radioactive.256.png",
    "40":":/icons/Icojam-Blue-Bits-Database-check.256.png",
    "41":":/icons/Icojam-Blue-Bits-Database-arrow-right.256.png",
    "42":":/icons/icons8-data-transfer-96.png",
    "43":":/icons/Icojam-Blue-Bits-Folder-check.256.png",
    "44":":/icons/icons8-database-restore-96.png",
    "45":":/icons/button_play_icon.png",
    "46":":/icons/Icojam-Blue-Bits-Database-add.256.png",
    "47":":/icons/document_icon.png",
    "48":":/icons/icons8-document-94.png",
    "49":":/icons/Icojam-Blue-Bits-Information.256.png",
    "50":":/icons/Icojam-Blue-Bits-Document-write.256.png",
    "51":":/icons/Icojam-Blue-Bits-Folder-delete.256.png",
    "52":":/icons/Icojam-Blue-Bits-Document-blue.256.png",
    "53":":/icons/Icojam-Blue-Bits-Folder.256.png",
    "54":":/icons/explorer_file_icon.png",
    "55":":/icons/Icojam-Blue-Bits-Search.256.png",
    "56":":/icons/icons8-versions-96.png",
    "57":":/icons/icons8-open-with-96.png",
    "58":":/icons/icons8-restore-page-96.png",
    "59":":/icons/Icojam-Blue-Bits-Shield.256.png",
    "60":":/icons/Icojam-Blue-Bits-Folder-arrow-right.256.png",
    "61":":/icons/download_icon.png",
    "62":":/icons/Icojam-Blue-Bits-Tool-edit.256.png",
    "63":":/icons/Icojam-Blue-Bits-Database-delete.256.png",
    "64":":/icons/Icojam-Blue-Bits-Arrow-left.256.png",
    "65":":/icons/Icojam-Blue-Bits-Document-photo.256.png",
    "66":":/icons/save_file_icon.png",
    "67":":/icons/Icojam-Blue-Bits-Database-arrow-up.256.png",
    "68":":/icons/bin_icon.png",
    "69":":/icons/Icojam-Blue-Bits-Document-arrow-up.256.png",
    "70":":/icons/Icojam-Blue-Bits-Database.256.png",
    "71":":/icons/Icojam-Blue-Bits-Document-search.256.png",
    "72":":/icons/Icojam-Blue-Bits-Arrow-right.256.png",
    "73":":/icons/settings_icon.png",
    "74":":/icons/Icojam-Blue-Bits-Math-add.256.png",
    "75":":/icons/Icojam-Blue-Bits-Folder-search.256.png",
    "76":":/icons/icons8-project-setup-96.png",
    "77":":/icons/Icojam-Blue-Bits-Document-add.256.png",
    "78":":/icons/Icojam-Blue-Bits-Math-minus.256.png",
    "79":":/icons/Icojam-Blue-Bits-Pinions-settings.256.png",
    "80":":/icons/Icojam-Blue-Bits-Document-arrow-down.256.png",
    "81":":/icons/Icojam-Blue-Bits-Chat-comment.256.png",
    "82":":/icons/icons8-business-report-96.png",
    "83":":/icons/Icojam-Blue-Bits-Database-search.256.png",
    "84":":/icons/Icojam-Blue-Bits-Folder-add.256.png",
    "85":":/icons/Icojam-Blue-Bits-Pinion-settings.256.png",
    "86":":/icons/Icojam-Blue-Bits-Document-remove.256.png",
    "87":":/icons/Icojam-Blue-Bits-Module-puzzle.256.png",
    "88":":/icons/Icojam-Blue-Bits-Folder-arrow-up.256.png",
    "89":":/icons/Icojam-Blue-Bits-Arrow-down.256.png",
    "90":":/icons/Icojam-Blue-Bits-Love-heart.256.png",
    "91":":/icons/Icojam-Blue-Bits-Database-settings.256.png",
    "92":":/icons/Icojam-Blue-Bits-Document-arrow-right.256.png",
    "93":":/icons/download_all_icon.png",

    }

class Icons:

    _paths = {
        "green arrow dn":":/icons/download_selected_icon.png",
        "db key":":/icons/icons8-data-encryption-80.png",
        "search file":":/icons/icons8-view-94.png",
        "trash":":/icons/icons8-trash-can-96.png",
        "pause":":/icons/button_pause_icon.png",
        "clear":":/icons/clear_icon.png",
        "folder download":":/icons/download_folder_icon.png",
        "info":":/icons/info_icon.png",
        "add file":":/icons/icons8-add-file-94.png",
        "goto file":":/icons/icons8-symlink-file-96.png",
        "plus":":/icons/plus_icon.png",
        "main":":/icons/main_icon.png",
        "yes":":/icons/yes_icon.png",
        "open file":":/icons/open_file_icon.png",
        "db admin":":/icons/icons8-database-administrator-94.png",
        "minus":":/icons/minus_icon.png",
        "tree nodes add":":/icons/icons8-add-subnode-96.png",
        "toggle":":/icons/toggle_icon.png",
        "purple toggle":":/icons/icons8-data-transfer-96.png",
        "db pink arrow":":/icons/icons8-database-restore-96.png",
        "play":":/icons/button_play_icon.png",
        "white document":":/icons/document_icon.png",
        "document":":/icons/icons8-document-94.png",
        "search folder":":/icons/explorer_file_icon.png",
        "file versions":":/icons/icons8-versions-96.png",
        "lists pink arrow":":/icons/icons8-open-with-96.png",
        "refresh file":":/icons/icons8-restore-page-96.png",
        "cloud download":":/icons/download_icon.png",
        "save file":":/icons/save_file_icon.png",
        "bin":":/icons/bin_icon.png",
        "settings":":/icons/settings_icon.png",
        "map settings":":/icons/icons8-project-setup-96.png",
        "report":":/icons/icons8-business-report-96.png",
        "bluegreen up dw arrows":":/icons/download_all_icon.png",
        "databases": ":/icons/Icojam-Blue-Bits-Database.256.png",
        "pen": ":/icons/Icojam-Blue-Bits-Pen-write.256.png",
        "db": ":/icons/Icojam-Blue-Bits-Database.256.png",
        "db add": ":/icons/Icojam-Blue-Bits-Database-add.256.png",
        "db remove": ":/icons/Icojam-Blue-Bits-Database-remove.256.png",
        "db activate": ":/icons/Icojam-Blue-Bits-Database-check.256.png",
        "db deactivate": ":/icons/Icojam-Blue-Bits-Database-delete.256.png",
        "db search": ":/icons/Icojam-Blue-Bits-Database-search.256.png",
        "db settings": ":/icons/Icojam-Blue-Bits-Database-settings.256.png",
        "folder ok": ":/icons/Icojam-Blue-Bits-Folder-check.256.png",
        "folder not ok": ":/icons/Icojam-Blue-Bits-Folder-delete.256.png",
        "shield": ":/icons/Icojam-Blue-Bits-Shield.256.png",
        "update file": ":/icons/icons8-symlink-file-96.png",
        "star": ":/icons/Icojam-Blue-Bits-Star-rating.256.png",
        "heart": ":/icons/Icojam-Blue-Bits-Love-heart.256.png",

    }

    _cache = {}

    @classmethod
    def icon(cls, name: str) -> QIcon:
        if name not in cls._cache:
            cls._cache[name] = QIcon(cls._paths.get(name,ICON_MAP["0"]))
        return cls._cache[name]