# icons.py

from PyQt6.QtGui import QIcon
import resources

ICON_MAP = {
    "0":":/icons/Icojam-Blue-Bits-Thumbs-up.256.png",
    "1":":/icons/Ahmadhania-Spherical-Right-bottom.128.png",
    "2":":/icons/Ahmadhania-Spherical-Technorati.128.png",
    "3":":/icons/Ahmadhania-Spherical-Options-1.128.png",
    "4":":/icons/Ahmadhania-Spherical-Usb.128.png",
    "5":":/icons/Ahmadhania-Spherical-Align-hor-center.128.png",
    "6":":/icons/Icojam-Blue-Bits-Folder-settings.256.png",
    "7":":/icons/download_selected_icon.png",
    "8":":/icons/icons8-data-encryption-80.png",
    "9":":/icons/Ahmadhania-Spherical-Designfloat.128.png",
    "10":":/icons/icons8-view-94.png",
    "11":":/icons/Ahmadhania-Spherical-Center-bottom.128.png",
    "12":":/icons/Ahmadhania-Spherical-Blinklist.128.png",
    "13":":/icons/Ahmadhania-Spherical-Recycle.128.png",
    "14":":/icons/icons8-trash-can-96.png",
    "15":":/icons/Icojam-Blue-Bits-Document-check.256.png",
    "16":":/icons/Ahmadhania-Spherical-Time.128.png",
    "17":":/icons/Ahmadhania-Spherical-Align-ver-center.128.png",
    "18":":/icons/Ahmadhania-Spherical-Satellite.128.png",
    "19":":/icons/Ahmadhania-Spherical-Gift.128.png",
    "20":":/icons/button_pause_icon.png",
    "21":":/icons/Icojam-Blue-Bits-Folder-images.256.png",
    "22":":/icons/Ahmadhania-Spherical-No-smoking.128.png",
    "23":":/icons/Ahmadhania-Spherical-Center-center.128.png",
    "24":":/icons/Ahmadhania-Spherical-Search.128.png",
    "25":":/icons/Ahmadhania-Spherical-Tv.128.png",
    "26":":/icons/Ahmadhania-Spherical-Options.128.png",
    "27":":/icons/Icojam-Blue-Bits-Star-rating.256.png",
    "28":":/icons/clear_icon.png",
    "29":":/icons/download_folder_icon.png",
    "30":":/icons/Ahmadhania-Spherical-Play.128.png",
    "31":":/icons/Ahmadhania-Spherical-Shopping-cart.128.png",
    "32":":/icons/Ahmadhania-Spherical-File-text.128.png",
    "33":":/icons/Ahmadhania-Spherical-File-remove.128.png",
    "34":":/icons/Ahmadhania-Spherical-Configuration.128.png",
    "35":":/icons/info_icon.png",
    "36":":/icons/Ahmadhania-Spherical-Info.128.png",
    "37":":/icons/Icojam-Blue-Bits-Pen-write.256.png",
    "38":":/icons/icons8-add-file-94.png",
    "39":":/icons/Ahmadhania-Spherical-Help.128.png",
    "40":":/icons/Ahmadhania-Spherical-Align-left.128.png",
    "41":":/icons/icons8-symlink-file-96.png",
    "42":":/icons/plus_icon.png",
    "43":":/icons/Ahmadhania-Spherical-Write-1.128.png",
    "44":":/icons/main_icon.png",
    "45":":/icons/Ahmadhania-Spherical-Select-text.128.png",
    "46":":/icons/Ahmadhania-Spherical-Paper-clip.128.png",
    "47":":/icons/Ahmadhania-Spherical-Align-top.128.png",
    "48":":/icons/Icojam-Blue-Bits-Document-empty.256.png",
    "49":":/icons/Ahmadhania-Spherical-Back.128.png",
    "50":":/icons/Ahmadhania-Spherical-Center-left.128.png",
    "51":":/icons/Ahmadhania-Spherical-Pause.128.png",
    "52":":/icons/yes_icon.png",
    "53":":/icons/Icojam-Blue-Bits-Document-delete.256.png",
    "54":":/icons/Ahmadhania-Spherical-Resize-diag-2.128.png",
    "55":":/icons/Ahmadhania-Spherical-Redo.128.png",
    "56":":/icons/Icojam-Blue-Bits-Document-arrow-left.256.png",
    "57":":/icons/open_file_icon.png",
    "58":":/icons/Icojam-Blue-Bits-Database-remove.256.png",
    "59":":/icons/Ahmadhania-Spherical-Connect.128.png",
    "60":":/icons/Icojam-Blue-Bits-Database-arrow-down.256.png",
    "61":":/icons/Ahmadhania-Spherical-Del.ico.us.128.png",
    "62":":/icons/icons8-database-administrator-94.png",
    "63":":/icons/Ahmadhania-Spherical-Configuration-1.128.png",
    "64":":/icons/Ahmadhania-Spherical-Battery-empty.128.png",
    "65":":/icons/Icojam-Blue-Bits-Warning.256.png",
    "66":":/icons/Icojam-Blue-Bits-Database-arrow-left.256.png",
    "67":":/icons/Icojam-Blue-Bits-Folder-arrow-left.256.png",
    "68":":/icons/Ahmadhania-Spherical-Burn.128.png",
    "69":":/icons/Icojam-Blue-Bits-Arrow-up.256.png",
    "70":":/icons/Ahmadhania-Spherical-File-configuration.128.png",
    "71":":/icons/Icojam-Blue-Bits-Document-settings.256.png",
    "72":":/icons/minus_icon.png",
    "73":":/icons/Ahmadhania-Spherical-Easy-access.128.png",
    "74":":/icons/Icojam-Blue-Bits-Symbol-delete.256.png",
    "75":":/icons/Ahmadhania-Spherical-Favorites.128.png",
    "76":":/icons/Ahmadhania-Spherical-Paint.128.png",
    "77":":/icons/Ahmadhania-Spherical-Write.128.png",
    "78":":/icons/Ahmadhania-Spherical-Pin.128.png",
    "79":":/icons/Icojam-Blue-Bits-Folder-arrow-down.256.png",
    "80":":/icons/Ahmadhania-Spherical-Digg.128.png",
    "81":":/icons/Ahmadhania-Spherical-Home.128.png",
    "82":":/icons/Ahmadhania-Spherical-Restart.128.png",
    "83":":/icons/Ahmadhania-Spherical-Palm-print.128.png",
    "84":":/icons/Ahmadhania-Spherical-Left-bottom.128.png",
    "85":":/icons/Ahmadhania-Spherical-Blogmarks.128.png",
    "86":":/icons/Ahmadhania-Spherical-Restore.128.png",
    "87":":/icons/Ahmadhania-Spherical-Users.128.png",
    "88":":/icons/Ahmadhania-Spherical-Window.128.png",
    "89":":/icons/icons8-add-subnode-96.png",
    "90":":/icons/Ahmadhania-Spherical-Save.128.png",
    "91":":/icons/Ahmadhania-Spherical-Previous-track.128.png",
    "92":":/icons/Icojam-Blue-Bits-Document-checkbox.256.png",
    "93":":/icons/Ahmadhania-Spherical-Scroll-up.128.png",
    "94":":/icons/Icojam-Blue-Bits-Symbol-check.256.png",
    "95":":/icons/Ahmadhania-Spherical-File-edit.128.png",
    "96":":/icons/Ahmadhania-Spherical-Scroll-right.128.png",
    "97":":/icons/Icojam-Blue-Bits-Question-faq.256.png",
    "98":":/icons/toggle_icon.png",
    "99":":/icons/Ahmadhania-Spherical-Stop.128.png",
    "100":":/icons/Icojam-Blue-Bits-Radioactive.256.png",
    "101":":/icons/Icojam-Blue-Bits-Database-check.256.png",
    "102":":/icons/Icojam-Blue-Bits-Database-arrow-right.256.png",
    "103":":/icons/icons8-data-transfer-96.png",
    "104":":/icons/Ahmadhania-Spherical-Mac.128.png",
    "105":":/icons/Icojam-Blue-Bits-Folder-check.256.png",
    "106":":/icons/icons8-database-restore-96.png",
    "107":":/icons/button_play_icon.png",
    "108":":/icons/Ahmadhania-Spherical-Files-add.128.png",
    "109":":/icons/Ahmadhania-Spherical-Keyboard.128.png",
    "110":":/icons/Icojam-Blue-Bits-Database-add.256.png",
    "111":":/icons/Ahmadhania-Spherical-Fast-forward.128.png",
    "112":":/icons/document_icon.png",
    "113":":/icons/Ahmadhania-Spherical-Mouse.128.png",
    "114":":/icons/Ahmadhania-Spherical-Heart.128.png",
    "115":":/icons/Ahmadhania-Spherical-Minimize.128.png",
    "116":":/icons/icons8-document-94.png",
    "117":":/icons/Ahmadhania-Spherical-Email.128.png",
    "118":":/icons/Ahmadhania-Spherical-Copyright.128.png",
    "119":":/icons/Ahmadhania-Spherical-Save-as.128.png",
    "120":":/icons/Ahmadhania-Spherical-Volume-2.128.png",
    "121":":/icons/Ahmadhania-Spherical-Molecule.128.png",
    "122":":/icons/Ahmadhania-Spherical-Plus.128.png",
    "123":":/icons/Icojam-Blue-Bits-Information.256.png",
    "124":":/icons/Icojam-Blue-Bits-Document-write.256.png",
    "125":":/icons/Ahmadhania-Spherical-Shield.128.png",
    "126":":/icons/Ahmadhania-Spherical-Mouse-curser.128.png",
    "127":":/icons/Ahmadhania-Spherical-Next-track.128.png",
    "128":":/icons/Ahmadhania-Spherical-Mute.128.png",
    "129":":/icons/Ahmadhania-Spherical-Error.128.png",
    "130":":/icons/Ahmadhania-Spherical-Mobile.128.png",
    "131":":/icons/Ahmadhania-Spherical-Edit.128.png",
    "132":":/icons/Icojam-Blue-Bits-Folder-delete.256.png",
    "133":":/icons/Icojam-Blue-Bits-Document-blue.256.png",
    "134":":/icons/Ahmadhania-Spherical-Cd.128.png",
    "135":":/icons/Ahmadhania-Spherical-Top.128.png",
    "136":":/icons/Ahmadhania-Spherical-Move.128.png",
    "137":":/icons/Icojam-Blue-Bits-Folder.256.png",
    "138":":/icons/Ahmadhania-Spherical-Calculator.128.png",
    "139":":/icons/explorer_file_icon.png",
    "140":":/icons/Icojam-Blue-Bits-Search.256.png",
    "141":":/icons/Ahmadhania-Spherical-Umbrella.128.png",
    "142":":/icons/icons8-versions-96.png",
    "143":":/icons/Ahmadhania-Spherical-Delete.128.png",
    "144":":/icons/icons8-open-with-96.png",
    "145":":/icons/Ahmadhania-Spherical-Nuclear.128.png",
    "146":":/icons/icons8-restore-page-96.png",
    "147":":/icons/Icojam-Blue-Bits-Shield.256.png",
    "148":":/icons/Ahmadhania-Spherical-Ok.128.png",
    "149":":/icons/Icojam-Blue-Bits-Folder-arrow-right.256.png",
    "150":":/icons/Ahmadhania-Spherical-Battery-full.128.png",
    "151":":/icons/Ahmadhania-Spherical-Ma.gnolia.128.png",
    "152":":/icons/download_icon.png",
    "153":":/icons/Icojam-Blue-Bits-Tool-edit.256.png",
    "154":":/icons/Ahmadhania-Spherical-Resize-hor.128.png",
    "155":":/icons/Ahmadhania-Spherical-Listen-to-music.128.png",
    "156":":/icons/Ahmadhania-Spherical-Sitemap.128.png",
    "157":":/icons/Ahmadhania-Spherical-Undo.128.png",
    "158":":/icons/Ahmadhania-Spherical-Resize-diag-1.128.png",
    "159":":/icons/Ahmadhania-Spherical-Down.128.png",
    "160":":/icons/Icojam-Blue-Bits-Database-delete.256.png",
    "161":":/icons/Ahmadhania-Spherical-Mute-2.128.png",
    "162":":/icons/Ahmadhania-Spherical-Scroll-down.128.png",
    "163":":/icons/Icojam-Blue-Bits-Arrow-left.256.png",
    "164":":/icons/Icojam-Blue-Bits-Document-photo.256.png",
    "165":":/icons/save_file_icon.png",
    "166":":/icons/Ahmadhania-Spherical-Rss.128.png",
    "167":":/icons/Icojam-Blue-Bits-Database-arrow-up.256.png",
    "168":":/icons/Ahmadhania-Spherical-Bluetooth.128.png",
    "169":":/icons/bin_icon.png",
    "170":":/icons/Icojam-Blue-Bits-Document-arrow-up.256.png",
    "171":":/icons/Ahmadhania-Spherical-Center-right.128.png",
    "172":":/icons/Ahmadhania-Spherical-Butterfly.128.png",
    "173":":/icons/Ahmadhania-Spherical-Target.128.png",
    "174":":/icons/Ahmadhania-Spherical-Left-top.128.png",
    "175":":/icons/Ahmadhania-Spherical-Airplane.128.png",
    "176":":/icons/Ahmadhania-Spherical-Forward.128.png",
    "177":":/icons/Icojam-Blue-Bits-Database.256.png",
    "178":":/icons/Icojam-Blue-Bits-Document-search.256.png",
    "179":":/icons/Icojam-Blue-Bits-Arrow-right.256.png",
    "180":":/icons/Ahmadhania-Spherical-Cut.128.png",
    "181":":/icons/Ahmadhania-Spherical-Power.128.png",
    "182":":/icons/Ahmadhania-Spherical-Fast-backward.128.png",
    "183":":/icons/Ahmadhania-Spherical-Ship.128.png",
    "184":":/icons/Ahmadhania-Spherical-Phone.128.png",
    "185":":/icons/settings_icon.png",
    "186":":/icons/Icojam-Blue-Bits-Math-add.256.png",
    "187":":/icons/Icojam-Blue-Bits-Folder-search.256.png",
    "188":":/icons/Ahmadhania-Spherical-Movie.128.png",
    "189":":/icons/icons8-project-setup-96.png",
    "190":":/icons/Icojam-Blue-Bits-Document-add.256.png",
    "191":":/icons/Icojam-Blue-Bits-Math-minus.256.png",
    "192":":/icons/Ahmadhania-Spherical-File-new.128.png",
    "193":":/icons/Icojam-Blue-Bits-Pinions-settings.256.png",
    "194":":/icons/Icojam-Blue-Bits-Document-arrow-down.256.png",
    "195":":/icons/Icojam-Blue-Bits-Chat-comment.256.png",
    "196":":/icons/icons8-business-report-96.png",
    "197":":/icons/Icojam-Blue-Bits-Database-search.256.png",
    "198":":/icons/Icojam-Blue-Bits-Folder-add.256.png",
    "199":":/icons/Ahmadhania-Spherical-Bomb.128.png",
    "200":":/icons/Icojam-Blue-Bits-Pinion-settings.256.png",
    "201":":/icons/Ahmadhania-Spherical-File-copy.128.png",
    "202":":/icons/Icojam-Blue-Bits-Document-remove.256.png",
    "203":":/icons/Icojam-Blue-Bits-Module-puzzle.256.png",
    "204":":/icons/Icojam-Blue-Bits-Folder-arrow-up.256.png",
    "205":":/icons/Ahmadhania-Spherical-Network.128.png",
    "206":":/icons/Ahmadhania-Spherical-Close.128.png",
    "207":":/icons/Ahmadhania-Spherical-Users-1.128.png",
    "208":":/icons/Ahmadhania-Spherical-Resize-ver.128.png",
    "209":":/icons/Ahmadhania-Spherical-Align-right.128.png",
    "210":":/icons/Ahmadhania-Spherical-Waiting.128.png",
    "211":":/icons/Ahmadhania-Spherical-Minus.128.png",
    "212":":/icons/Ahmadhania-Spherical-Anti-virus.128.png",
    "213":":/icons/Ahmadhania-Spherical-Volume.128.png",
    "214":":/icons/Icojam-Blue-Bits-Arrow-down.256.png",
    "215":":/icons/Icojam-Blue-Bits-Love-heart.256.png",
    "216":":/icons/Ahmadhania-Spherical-File-download.128.png",
    "217":":/icons/Icojam-Blue-Bits-Database-settings.256.png",
    "218":":/icons/Icojam-Blue-Bits-Document-arrow-right.256.png",
    "219":":/icons/Ahmadhania-Spherical-Align-bottom.128.png",
    "220":":/icons/download_all_icon.png",
    "221":":/icons/Ahmadhania-Spherical-Right-top.128.png",
    "222":":/icons/Ahmadhania-Spherical-Printer.128.png",
    "223":":/icons/Ahmadhania-Spherical-File-media.128.png",
    "224":":/icons/Ahmadhania-Spherical-Key.128.png",
    "225":":/icons/Ahmadhania-Spherical-Scroll-left.128.png",

    }
class Icons:

    _paths = {
        "green arrow dn":":/icons/download_selected_icon.png",
        "db key":":/icons/icons8-data-encryption-80.png",
        "search file":":/icons/icons8-view-94.png",
        "trash":":/icons/icons8-trash-can-96.png",
        "pause":":/icons/button_pause_icon.png",
        "clear":":/icons/clear_icon.png",
        "folder download":":/icons/download_folder_icon.png",
        "info":":/icons/info_icon.png",
        "add file":":/icons/icons8-add-file-94.png",
        "goto file":":/icons/icons8-symlink-file-96.png",
        "plus":":/icons/plus_icon.png",
        "main":":/icons/main_icon.png",
        "yes":":/icons/yes_icon.png",
        "open file":":/icons/open_file_icon.png",
        "db admin":":/icons/icons8-database-administrator-94.png",
        "minus":":/icons/minus_icon.png",
        "tree nodes add":":/icons/icons8-add-subnode-96.png",
        "toggle":":/icons/toggle_icon.png",
        "purple toggle":":/icons/icons8-data-transfer-96.png",
        "db pink arrow":":/icons/icons8-database-restore-96.png",
        "play blue":":/icons/button_play_icon.png",
        "white document":":/icons/document_icon.png",
        "document":":/icons/icons8-document-94.png",
        "search folder":":/icons/explorer_file_icon.png",
        "file versions":":/icons/icons8-versions-96.png",
        "lists pink arrow":":/icons/icons8-open-with-96.png",
        "refresh file":":/icons/icons8-restore-page-96.png",
        "cloud download":":/icons/download_icon.png",
        "save file":":/icons/save_file_icon.png",
        "bin":":/icons/bin_icon.png",
        "settings":":/icons/settings_icon.png",
        "map settings":":/icons/icons8-project-setup-96.png",
        "report":":/icons/icons8-business-report-96.png",
        "bluegreen up dw arrows":":/icons/download_all_icon.png",
        "databases": ":/icons/Icojam-Blue-Bits-Database.256.png",
        "pen": ":/icons/Icojam-Blue-Bits-Pen-write.256.png",
        "db": ":/icons/Icojam-Blue-Bits-Database.256.png",
        "db add": ":/icons/Icojam-Blue-Bits-Database-add.256.png",
        "db remove": ":/icons/Icojam-Blue-Bits-Database-remove.256.png",
        "db activate": ":/icons/Icojam-Blue-Bits-Database-check.256.png",
        "db deactivate": ":/icons/Icojam-Blue-Bits-Database-delete.256.png",
        "db search": ":/icons/Icojam-Blue-Bits-Database-search.256.png",
        "db settings": ":/icons/Icojam-Blue-Bits-Database-settings.256.png",
        "folder ok": ":/icons/Icojam-Blue-Bits-Folder-check.256.png",
        "folder not ok": ":/icons/Icojam-Blue-Bits-Folder-delete.256.png",
        "shield": ":/icons/Icojam-Blue-Bits-Shield.256.png",
        "update file": ":/icons/icons8-symlink-file-96.png",
        "star": ":/icons/Icojam-Blue-Bits-Star-rating.256.png",
        "heart": ":/icons/Icojam-Blue-Bits-Love-heart.256.png",
        
        "devices": ":/icons/Ahmadhania-Spherical-Usb.128.png",
        "refresh": ":/icons/Ahmadhania-Spherical-Redo.128.png",        
        "key": ":/icons/Ahmadhania-Spherical-Key.128.png",
        "home": ":/icons/Ahmadhania-Spherical-Home.128.png",
        "pin": ":/icons/Ahmadhania-Spherical-Pin.128.png",
        "details": ":/icons/Ahmadhania-Spherical-Target.128.png",

        "mapping":":/icons/Ahmadhania-Spherical-Sitemap.128.png",
        "device map":":/icons/Ahmadhania-Spherical-Time.128.png",
        "keep map":":/icons/Ahmadhania-Spherical-Ok.128.png",
        "remove map":":/icons/Ahmadhania-Spherical-Close.128.png",
        "selection map":":/icons/Ahmadhania-Spherical-Mouse-curser.128.png",
        "backup map":":/icons/Ahmadhania-Spherical-Palm-print.128.png",

        "stop":":/icons/Ahmadhania-Spherical-Stop.128.png",
        "play":":/icons/Ahmadhania-Spherical-Play.128.png",
        "shallow":":/icons/Ahmadhania-Spherical-Calculator.128.png",

        "clone":":/icons/Ahmadhania-Spherical-Del.ico.us.128.png",
        "rename":":/icons/Ahmadhania-Spherical-Keyboard.128.png",
        "delete map":":/icons/Ahmadhania-Spherical-Delete.128.png",
        "update map":":/icons/Ahmadhania-Spherical-Redo.128.png", 
        "continue mapping":":/icons/Ahmadhania-Spherical-Blinklist.128.png", 
        "find duplicates":":/icons/Ahmadhania-Spherical-File-copy.128.png", 
        "find repeated":":/icons/icons8-versions-96.png", 
        "search map":":/icons/icons8-view-94.png",
        "tree" :":/icons/icons8-add-subnode-96.png",
        "dir explore" :":/icons/explorer_file_icon.png",
        "file struct" :":/icons/icons8-open-with-96.png",
        "data list" :":/icons/Icojam-Blue-Bits-Document-checkbox.256.png",
        "shallow compare" :":/icons/Ahmadhania-Spherical-Resize-hor.128.png",
        "deep compare" :":/icons/Ahmadhania-Spherical-Resize-ver.128.png",
        

        
    }

    _cache = {}

    @classmethod
    def icon(cls, name: str) -> QIcon:
        if name not in cls._cache:
            cls._cache[name] = QIcon(cls._paths.get(name,ICON_MAP["0"]))
        return cls._cache[name]